In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from dotenv import load_dotenv
import os

pd.set_option('display.max_columns', None)
%matplotlib inline

In [2]:
import pandas as pd
import requests
import requests

def download_from_drive(file_id, destination):
    url = "https://drive.google.com/uc?export=download"
    session = requests.Session()
    response = session.get(url, params={'id': file_id}, stream=True)

    token = None
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            token = value

    if token:
        response = session.get(url, params={'id': file_id, 'confirm': token}, stream=True)

    with open(destination, 'wb') as f:
        for chunk in response.iter_content(32768):
            if chunk:
                f.write(chunk)

visits_id = "1QosQQ4RRNR9rkL4t7sB707h2Uy0XfYJe"
signups_id = "1AeQz0kaSgz0lxYSDtuNm36muhy5fRCzZ"

download_from_drive(visits_id, "visitas.csv")
download_from_drive(signups_id, "inscripciones.csv")

visits = pd.read_csv("visitas.csv")
signups = pd.read_csv("inscripciones.csv")

print("Visitas:", visits.shape)
print("Inscripciones:", signups.shape)

Visitas: (1000, 4)
Inscripciones: (1000, 5)

In [4]:
visits.head()

,uuid,platform,user_agent,date
0,1de9ea66-70d3-4a1f-8735-df5ef7697fb9,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,2023-03-01T13:29:22
1,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-01T16:44:28
2,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-06T06:12:36
3,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-01T20:16:37
4,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-05T17:42:47

In [5]:
signups.head()

,date,user_id,email,platform,registration_type
0,2023-03-01T00:25:39,8838849,joseph95@example.org,web,google
1,2023-03-01T14:53:01,8741065,janetsuarez@example.net,web,yandex
2,2023-03-01T14:27:36,1866654,robert67@example.org,web,google
3,2023-03-01T02:42:34,1577584,elam@example.net,web,apple
4,2023-03-01T10:27:14,4765395,stephanie68@example.net,web,yandex

In [6]:
visits.describe(include='all')

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

In [7]:
signups.describe(include='all')

,date,user_id,email,platform,registration_type
count,1000,1.000000e+03,1000,1000,1000
unique,1000,NaN,997,3,4
top,2023-03-01T00:25:39,NaN,zanderson@example.org,android,email
freq,1,NaN,2,517,446
mean,NaN,4.488623e+06,NaN,NaN,NaN
std,NaN,2.620568e+06,NaN,NaN,NaN
min,NaN,2.236800e+04,NaN,NaN,NaN
25%,NaN,2.235489e+06,NaN,NaN,NaN
50%,NaN,4.473044e+06,NaN,NaN,NaN
75%,NaN,6.779707e+06,NaN,NaN,NaN
max,NaN,8.881772e+06,NaN,NaN,NaN

In [8]:
visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uuid        1000 non-null   object
 1   platform    1000 non-null   object
 2   user_agent  1000 non-null   object
 3   date        1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [9]:
signups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1000 non-null   object
 1   user_id            1000 non-null   int64
 2   email              1000 non-null   object
 3   platform           1000 non-null   object
 4   registration_type  1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [10]:
api_visits_url = "https://data-charts-api.hexlet.app/visits"
api_registrations_url = "https://data-charts-api.hexlet.app/registrations"

params = {
    "begin": "2023-03-01",
    "end": "2023-09-01"
}

response_visits = requests.get(api_visits_url, params=params)
response_registrations = requests.get(api_registrations_url, params=params)

print("Status visitas:", response_visits.status_code)
print("Status registros:", response_registrations.status_code)

Status visitas: 200
Status registros: 200

In [6]:
api_visits = pd.DataFrame(response_visits.json())
api_registrations = pd.DataFrame(response_registrations.json())

print("API Visitas:", api_visits.shape)
print("API Registros:", api_registrations.shape)

API Visitas: (263459, 4)
API Registros: (21836, 5)

In [7]:
api_visits.head()

,visit_id,platform,user_agent,datetime
0,a6fc64df-f1b9-4f6d-8d23-08a23d6946d0,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-08-07T09:07:37
1,a6fc64df-f1b9-4f6d-8d23-08a23d6946d0,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-08-04T09:31:21
2,a7abbf4b-1c20-4d00-989e-acd3ba8680e1,web,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,2023-08-07T05:59:04
3,a7abbf4b-1c20-4d00-989e-acd3ba8680e1,web,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,2023-08-06T00:50:59
4,a7abbf4b-1c20-4d00-989e-acd3ba8680e1,web,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,2023-08-05T11:15:18

In [8]:
api_registrations.head()

,datetime,user_id,email,platform,registration_type
0,2023-03-01T07:40:13,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ebyrd@example.org,web,google
1,2023-03-01T13:14:00,f007f97c-9d8b-48b5-af08-119bb8f6d9b6,knightgerald@example.org,web,email
2,2023-03-01T03:05:50,24ff46ae-32b3-4a74-8f27-7cf0b8f32f15,cherylthompson@example.com,web,apple
3,2023-03-01T00:04:47,3e9914e1-5d73-4c23-b25d-b59a3aeb2b60,halldavid@example.org,web,email
4,2023-03-01T18:31:52,27f875fc-f8ce-4aeb-8722-0ecb283d0760,denise86@example.net,web,google

In [11]:
api_visits['datetime'] = pd.to_datetime(api_visits['datetime'])
api_registrations['datetime'] = pd.to_datetime(api_registrations['datetime'])

# Excluir bots: los que tengan "bot" en platform o en user_agent
is_bot = (
    api_visits['platform'].str.contains('bot', case=False, na=False) |
    api_visits['user_agent'].str.contains('bot', case=False, na=False)
)
visits_clean = api_visits[~is_bot].copy()

# Quedarnos con la ÚLTIMA visita de cada visit_id
visits_clean = visits_clean.sort_values('datetime').drop_duplicates(subset='visit_id', keep='last')

print("Visitas totales:", len(api_visits))
print("Visitas sin bots ni duplicados:", len(visits_clean))

Visitas totales: 263459
Visitas sin bots ni duplicados: 138703

In [12]:
visits_clean['date_group'] = visits_clean['datetime'].dt.floor('D')

visits_grouped = (
    visits_clean.groupby(['date_group', 'platform'])
    .size()
    .reset_index(name='visits')
)
visits_grouped.head()

  date_group platform  visits
0 2023-03-01  android      75
1 2023-03-01      ios      22
2 2023-03-01      web     279
3 2023-03-02  android      67
4 2023-03-02      ios      31

In [13]:
api_registrations['date_group'] = api_registrations['datetime'].dt.floor('D')

registrations_grouped = (
    api_registrations.groupby(['date_group', 'platform'])
    .size()
    .reset_index(name='registrations')
)
registrations_grouped.head()

  date_group platform  registrations
0 2023-03-01  android             61
1 2023-03-01      ios             18
2 2023-03-01      web              8
3 2023-03-02  android             59
4 2023-03-02      ios             24

In [14]:
conversion = pd.merge(
    visits_grouped, registrations_grouped,
    on=['date_group', 'platform'], how='outer'
)
conversion['visits'] = conversion['visits'].fillna(0)
conversion['registrations'] = conversion['registrations'].fillna(0)

conversion['conversion'] = (conversion['registrations'] / conversion['visits']) * 100

conversion = conversion.sort_values('date_group').reset_index(drop=True)

conversion.head()

  date_group platform  visits  registrations  conversion
0 2023-03-01  android      75             61   81.333333
1 2023-03-01      ios      22             18   81.818182
2 2023-03-01      web     279              8    2.867384
3 2023-03-02  android      67             59   88.059701
4 2023-03-02      ios      31             24   77.419355

In [15]:
conversion.to_json("./conversion.json")
print("Archivo guardado ✅")

Archivo guardado ✅